name: Show error

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install meson
        run: pip3 install meson
      - name: Install ninja
        run: brew install ninja
      - name: Build arm64
        run: ./build-arm64.sh
      - name: Build x86_64
        run: ./build-x86.sh
      - name: Upload build/meson-logs/meson-log.txt as an artifact
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: meson-log
          path: build/meson-logs/meson-log.txt
