name: Show error

on:
  workflow_run: 
  push: 

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install meson
        run: pip install meson
      - name: Build arm64
        run: ./build-arm64.sh
      - name: Build x86_64
        run: ./build-x86_64.sh